version: '3.8'

services:
  react-app:
    image: node:14
    container_name: react-app
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - '3000:3000'
    command: sh -c "npm install && npm start"

#   mysql-db:
#     image: mysql:8.0
#     container_name: mysql-db
#     restart: always
#     environment:
#       MYSQL_ROOT_PASSWORD: your_root_password
#       MYSQL_DATABASE: your_database_name
#       MYSQL_USER: your_user
#       MYSQL_PASSWORD: your_password
#     ports:
#       - '3306:3306'
#     volumes:
#       - mysql-data:/var/lib/mysql

# volumes:
#   mysql-data:
